# Etapa 1: build do Angular
FROM node:22-alpine AS build

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build --configuration=production

# Etapa 2: servir com NGINX
FROM nginx:alpine

COPY --from=build /app/dist/casino-frontend/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]